# Site
title:          Osmond Chiu
bio:            'Public policy professional and advocate'
description:    "Public policy professional and advocate"
picture:        'assets/img/profile.jpg'
locale:         en_AU
url:            https://osmondchiu.github.io


# Jekyll
permalink:      /:title/
markdown:       kramdown
highlighter:    rouge
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
sass:
  sass_dir: _sass
  style: compressed

# Social
# if you don't have any of social below, comment the line.
email: osmond@osmondchiu.com.au
twitter: redrabbleroz
facebook: osmondchiualp
#google:
  #plus: #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
#github: username
linkedin: ochiu
#xing: username
#pinterest: username
#foursquare: username
#dribbble: username
#soundcloud: username
#weibo: username
#flickr: username
#codepen: username
mastodon: redrabbleroz@aus.social

# Paginate
# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"


# Comments
disqus_shortname: 


# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
